import { Wifi, Wind, Snowflake, Eye, Users, Home, Fan, Coffee, Utensils, Car, Droplets, Shield, DoorOpen, WashingMachine, Trees, Calendar, ShieldCheck, Castle  } from 'lucide-react';

// Complete amenity icon mapping for both villas
export const amenityIcons = {
  'Air conditioning': Snowflake,
  'Wi-fi': Wifi,
  'Wifi': Wifi,
  'Lake views': Eye,
  'Lake access': Eye,
  'Mosquito nets': Shield,
  'Mosquito net': Shield,
  'Sleeps six': Users,
  'Sleeps three': Users,
  'Bed linens': Home,
  'Ceiling fan': Fan,
  'Desk Space': Home,
  'BBQ grill': Coffee,
  'Refrigerator': Home,
  'Kitchen & equipments': Utensils,
  'Kitchen': Utensils,
  'Clothing storage': Home,
  'Dining table': Utensils,
  'Dishes and silverware': Utensils,
  'Free parking on premises': Car,
  'Hot water': Droplets,
  'Private living room': Home,
  'Private entrance': DoorOpen,
  'Private garden': Trees,
  'Private Backyard': Trees,
  'Safe place': Shield,
  'Washing machine': WashingMachine,
  'Patio': Home,
  'Essentials': Home,
  'Cooking basics': Coffee,
  'Hammock': Wind,
  'Long term stays allowed': Calendar,
  'Safe provided': ShieldCheck,
  'Private three balcony': Castle
};